# Generated by Django 5.2.8 on 2025-12-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscription_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesastatement',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesastatement',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
